# versioning
version: '0.0.{build}-{branch}'

# branches
branches:
  only:
    - tugait2018-feature1

# install phase
install:
  # to run script as a PowerShell command prepend it with ps:
  - ps: Write-Host 'This is PowerShell - install'

# build pahse
build_script:
  - ps: Write-Host "This is PowerShell - build"

# test phase
test_script:
  - ps: Write-Host "This is PowerShell - test"

