# versioning
version: '0.0.{build}-{branch}'

# Build worker image (VM template)
image: Visual Studio 2017

# branches
branches:
  only:
    - tugait2018-feature1

# Build worker image (VM template)
image: Visual Studio 2017

# test phase
test_script:
  - ps: .\tSQLt\ps\drop-db-test.ps1

# install phase
install:
  # to run script as a PowerShell command prepend it with ps:
  - ps: Write-Host 'This is PowerShell - install'

# build pahse
build_script:
  - ps: Write-Host "This is PowerShell - build"



