version: '0.0.{build}'

install:
  # to run script as a PowerShell command prepend it with ps:
  - ps: Write-Host 'This is PowerShell - install'


build_script:
  - ps: Write-Host "This is PowerShell - build"


test_script:
  - ps: Write-Host "This is PowerShell - test"

