# versioning
version: '0.0.{build}-{branch}'

# branches
branches:
  only:
    - tugait2018-feature1

# Build worker image (VM template)
image: Visual Studio 2017

# start SQL server service
services:
  - mssql2017

# build phase
build_script:
  - ps: .\tSQLt\ps\drop-db-test.ps1 "(local)\SQL2017" "sa" "Password12!"

# test phase
#test_script:
#  - ps: .\tSQLt\ps\drop-db-test.ps1

# install phase
install:
  # to run script as a PowerShell command prepend it with ps:
  - ps: Write-Host 'This is PowerShell - install'


