CREATE TABLE [dbo].[Meetup](
	[MeetupId] [INT] IDENTITY(1,1) NOT NULL,
	[MeetupName] [NVARCHAR](50) NULL,
	[MeetupDate] [DATETIME] NULL,
 CONSTRAINT [PK_Event] PRIMARY KEY CLUSTERED 
(
	[MeetuptId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
