CREATE TABLE [dbo].[Event](
	[EventId] [INT] IDENTITY(1,1) NOT NULL,
	[EventName] [NVARCHAR](50) NULL,
	[EventDate] [DATETIME] NULL,
 CONSTRAINT [PK_Event] PRIMARY KEY CLUSTERED 
(
	[EventId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
