# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main
  - demo
  - feature/*

pool:
  vmImage: windows-latest

steps:
- task: PowerShell@2
  inputs:
    filePath: 'build_db_nuspec.ps1'
    arguments: 'DevOpsPorto-Db'
  displayName: "create nuspec"

- task: PowerShell@2
  inputs:
    filePath: 'build_pack.ps1'
    arguments: 'DevOpsPorto-Db 123'
  displayName: "create nuspec"
